JMHa0206/spring_boot

pom.xml
src/main/java/com/kedu/study/controllers/AuthController.java
src/main/java/com/kedu/study/dao/EmployeeDAO.java
src/main/java/com/kedu/study/dto/DEMSCategoryDTO.java
src/main/java/com/kedu/study/dto/EDMSDTO.java
src/main/java/com/kedu/study/dto/EDMSFileDTO.java
src/main/java/com/kedu/study/dto/EDMSFormDTO.java
src/main/java/com/kedu/study/dto/EDMSSignOffDTO.java
src/main/java/com/kedu/study/dto/LoginResponseDTO.java
src/main/java/com/kedu/study/service/AuthService.java
src/main/java/com/kedu/study/utils/JWTUtil.java
src/main/resources/mapper/Employee-mapper.xml

XavierSmith25 / fixed all realted login / AuthController 등. Login 관련 코드 전부 작성 완료입니다_.

XavierSmith25 / fixed all realted login / AuthController 등.

---

src/main/java/com/kedu/study/controllers/ScheduleController.java
src/main/java/com/kedu/study/controllers/attendanceController.java
src/main/java/com/kedu/study/dto/ScheduleDTO.java
src/main/java/com/kedu/study/dto/activityDTO.java
src/main/java/com/kedu/study/dto/attendanceDTO.java

Schedule*.java라는 java 파일안에 있는 모든 내용들을 attendance*.java로 위치 변경
attendance 관련 DTO 생성

jeokaet/근태관리 작업에 필요한 java생성 및 post값 받는 위치 수정

---

pom.xml
src/main/java/com/kedu/study/config/WebSocketConfig.java
src/main/java/com/kedu/study/controllers/MessageController.java
src/main/java/com/kedu/study/controllers/MsgEmpController.java
src/main/java/com/kedu/study/dao/MsgEmpDAO.java
src/main/java/com/kedu/study/dto/MsgEmpDTO.java
src/main/java/com/kedu/study/service/MsgEmpService.java
src/main/resources/mapper/MsgEmp-mapper.xml

메세지 컨트롤러에 메소드 추가 / MsgEmp 컨트롤러 DAO DTO 서비스 mapper 추가 / config에 websocketconfig 추가

woong boot updated

---

src/main/java/com/kedu/study/controllers/AttendanceController.java
src/main/java/com/kedu/study/dao/AttendanceDAO.java
src/main/java/com/kedu/study/service/AttendanceService.java
src/main/resources/mapper/Attendance-mapper.xml

서비스부분에서 퇴근버튼에 대해 출근과 퇴근 시간 비교가 가능해지고 
날짜 데이터 값 변환에 대해 오류 수정
+ 오늘 출근 2번 못하게 막아버림 DAO에서 getTodayCheckIn 이녀석이 그 역할을 합니다.

jeokaet / 로그인 출 퇴근 및 시간 비교

---

src/main/java/com/kedu/study/controllers/BoardController.java
src/main/java/com/kedu/study/dao/BoardDAO.java
src/main/java/com/kedu/study/dto/BoardDTO.java
src/main/resources/mapper/Board_mapper.xml

board springboot 게시물 컬럼명만 간단히 작성했습니다

board springboot 게시물 컬럼명만 간단히 작성했습니다

---

src/main/java/com/kedu/study/controllers/AuthController.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSCategoryController.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSFileController.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSFormController.java
src/main/java/com/kedu/study/controllers/MessageController.java
src/main/java/com/kedu/study/controllers/MsgEmpController.java
src/main/java/com/kedu/study/dao/EDMS/EDMSFormDAO.java
src/main/java/com/kedu/study/dao/MsgEmpDAO.java
src/main/java/com/kedu/study/dto/ChatRoomDTO.java
src/main/java/com/kedu/study/dto/ChattingRoomDTO.java
src/main/java/com/kedu/study/dto/MadeChatRoomDTO.java
src/main/java/com/kedu/study/dto/MsgEmpMineDTO.java
src/main/java/com/kedu/study/security/JwtFilter.java
src/main/java/com/kedu/study/service/EDMS/EDMSCategoryService.java
src/main/java/com/kedu/study/service/EDMS/EDMSFileService.java
src/main/java/com/kedu/study/service/EDMS/EDMSSignOffService.java
src/main/java/com/kedu/study/service/MsgEmpService.java
src/main/resources/mapper/MsgEmp-mapper.xml

MsgEmpController,DAO,Service,mapper 수정 or 추가/ ChatRoomDTO,MadeChatRoomDTO,MsgEmpMineDTO 추가

월요일에 못한 풀리

---

src/main/java/com/kedu/study/controllers/EDMS/EDMSFormController.java

XavierSmith25 / EDMSFormController fix / EDMSFormController React 에서 양식조회를 위한 컨트롤러 구성입니다

XavierSmith25 / EDMSFormController fix / EDMSFormController

---

src/main/java/com/kedu/study/controllers/MessageController.java
src/main/java/com/kedu/study/service/EDMS/EDMSFormService.java
src/main/resources/application.properties
src/main/resources/mapper/EDMSForm-mapper.xml

XavierSmith25 / Fixed EDMSForm-Mapper / 매퍼수정입니다.

XavierSmith25 / Fixed EDMSForm-Mapper /

---

src/main/java/com/kedu/study/config/CORSConfig.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSController.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSEmpController.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSFileController.java
src/main/java/com/kedu/study/dao/EDMS/EDMSEmpDAO.java
src/main/java/com/kedu/study/service/EDMS/EDMSEmpService.java
src/main/resources/mapper/EDMS-mapper.xml
src/main/resources/mapper/EDMSCategory-mapper.xml
src/main/resources/mapper/Employee-mapper.xml

XavierSmith25 / EDMSEmp - / 코드추가

XavierSmith25 / EDMSEmp - / 코드추가

---

src/main/java/com/kedu/study/controllers/MessageController.java

1대1 채팅 오류 수정

---

src/main/java/com/kedu/study/controllers/MsgEmpController.java
src/main/java/com/kedu/study/controllers/MypageController.java
src/main/java/com/kedu/study/dao/MypageDAO.java
src/main/java/com/kedu/study/dto/DepartDTO.java
src/main/java/com/kedu/study/dto/EmployeeDTO.java
src/main/java/com/kedu/study/dto/JobDTO.java
src/main/java/com/kedu/study/service/MypageService.java
src/main/resources/mapper/Mypage-mapper.xml

Mypage에 필요한 컨트롤러 및 DAO DTO 등등 생성
추후 수정도 만들거라서 일단 출력만했습니다.

jeokaet / mypage 1

---

src/main/resources/mapper/EDMS-mapper.xml
src/main/resources/mapper/EDMSCategory-mapper.xml

XavierSmith25 / EDMS-mapper etc / EDMS 관련 작성기능 마감

XavierSmith25 / EDMS-mapper etc / EDMS 관련 작성기능 마감

---

src/main/java/com/kedu/study/controllers/MypageController.java
src/main/java/com/kedu/study/dao/MypageDAO.java
src/main/java/com/kedu/study/service/MypageService.java
src/main/resources/mapper/Mypage-mapper.xml

마이페이지 수정완!
일단 1단계만 완료
예외처리(이메일 @naver이나 net이나 이런거 아직 안해놈)못함

jeokaet/마이페이지 수정 및 출력 완료 찐

---

src/main/java/com/kedu/study/controllers/BoardController.java
src/main/java/com/kedu/study/controllers/BoardReplyController.java
src/main/java/com/kedu/study/dao/BoardDAO.java
src/main/java/com/kedu/study/dao/BoardReplyDAO.java
src/main/java/com/kedu/study/dto/BoardDTO.java
src/main/java/com/kedu/study/dto/BoardReplyDTO.java
src/main/java/com/kedu/study/service/BoardReplyService.java
src/main/java/com/kedu/study/service/BoardService.java
src/main/resources/mapper/Board-mapper.xml
src/main/resources/mapper/BoardReply-mapper.xml

게시물 crud table 수정중/댓글 crud까지 했습니다

게시물 crud table 수정중/댓글 crud까지 했습니다

---

src/main/java/com/kedu/study/config/ResourceConfig.java
src/main/java/com/kedu/study/controllers/MypageController.java
src/main/java/com/kedu/study/dao/MypageDAO.java
src/main/java/com/kedu/study/dto/EmployeeDTO.java
src/main/java/com/kedu/study/dto/ProfileImgDTO.java
src/main/java/com/kedu/study/service/MypageService.java
src/main/resources/mapper/Mypage-mapper.xml

jeokaet / mypage 프로필 뜸 찐

---

src/main/java/com/kedu/study/controllers/EDMS/EDMSController.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSEmpController.java
src/main/java/com/kedu/study/dao/EDMS/EDMSDAO.java
src/main/java/com/kedu/study/dao/EDMS/EDMSEmpDAO.java
src/main/java/com/kedu/study/dto/ApproverInfoDTO.java
src/main/java/com/kedu/study/dto/EDMSDTO.java
src/main/java/com/kedu/study/service/EDMS/EDMSEmpService.java
src/main/java/com/kedu/study/service/EDMS/EDMSService.java
src/main/resources/mapper/EDMS-mapper.xml
src/main/resources/mapper/Employee-mapper.xml

XavierSmith25 / EDMS Expression 50% fin /  관련 데이터입니다

XavierSmith25 / EDMS Expression 50% fin / 

---

src/main/java/com/kedu/study/config/CORSConfig.java
src/main/java/com/kedu/study/controllers/AttendanceController.java
src/main/java/com/kedu/study/dao/AttendanceDAO.java
src/main/java/com/kedu/study/service/AttendanceService.java
src/main/resources/mapper/Attendance-mapper.xml

jeokaet / 업무 외근 완?

---

src/main/java/com/kedu/study/config/CORSConfig.java
src/main/java/com/kedu/study/controllers/BoardController.java
src/main/java/com/kedu/study/controllers/BoardFileController.java
src/main/java/com/kedu/study/dao/BoardDAO.java
src/main/java/com/kedu/study/dao/BoardFileDAO.java
src/main/java/com/kedu/study/dto/BoardDTO.java
src/main/java/com/kedu/study/dto/BoardFileDTO.java
src/main/java/com/kedu/study/service/BoardFileService.java
src/main/java/com/kedu/study/service/BoardService.java
src/main/resources/mapper/Board-mapper.xml
src/main/resources/mapper/BoardFile-mapper.xml

게시글 조회수 추천수 게시글 입력까지 완료했습니다 

---

src/main/java/com/kedu/study/config/CORSConfig.java
src/main/java/com/kedu/study/controllers/EDMS/EDMSController.java
src/main/java/com/kedu/study/dao/EDMS/EDMSDAO.java
src/main/java/com/kedu/study/dao/EDMS/EDMSEmpDAO.java
src/main/java/com/kedu/study/service/EDMS/EDMSEmpService.java
src/main/java/com/kedu/study/service/EDMS/EDMSService.java
src/main/resources/mapper/EDMS-mapper.xml
src/main/resources/mapper/Employee-mapper.xml

XavierSmith25 / EDMSList / 

---

src/main/java/com/kedu/study/dto/LeaveDTO.java
src/main/java/com/kedu/study/dto/TripDTO.java
src/main/java/com/kedu/study/service/InsaService.java
src/main/resources/mapper/insa-mapper.xml

휴가 / 출장 기록관리 페이지에서 개인 출장 및 부서휴가, 오늘 출근한 사람 체크가능

jeokaet / 휴가 출장 오늘 출근 유무

---

src/main/java/com/kedu/study/config/CORSConfig.java
src/main/java/com/kedu/study/controllers/InsaController.java
src/main/java/com/kedu/study/dao/InsaDAO.java
src/main/java/com/kedu/study/dto/OvertimeDTO.java
src/main/java/com/kedu/study/service/AttendanceService.java
src/main/java/com/kedu/study/service/InsaService.java
src/main/resources/mapper/Attendance-mapper.xml
src/main/resources/mapper/insa-mapper.xml

jeokaet / 출근 및 보조 1단계 완료 + 휴가 / 출장 / 초과근무 목록 조회 완료 

---

src/main/java/com/kedu/study/config/CORSConfig.java
src/main/java/com/kedu/study/controllers/MsgEmpController.java
src/main/java/com/kedu/study/dao/MsgEmpDAO.java
src/main/java/com/kedu/study/service/MsgEmpService.java
src/main/resources/mapper/MsgEmp-mapper.xml

메신저 삭제기능 추가 및 피드백

---

src/main/java/com/kedu/study/controllers/InsaController.java
src/main/java/com/kedu/study/dao/InsaDAO.java
src/main/java/com/kedu/study/dto/DepartmentAttendanceDTO.java
src/main/java/com/kedu/study/dto/Departsimple.java
src/main/java/com/kedu/study/service/InsaService.java
src/main/java/com/kedu/study/service/ReserveService.java
src/main/resources/mapper/insa-mapper.xml

jeokaet / 부서별 출 / 퇴근 및 근무기록 조회 찐완

---

src/main/java/com/kedu/study/controllers/BoardController.java
src/main/java/com/kedu/study/dao/BoardDAO.java
src/main/java/com/kedu/study/dto/BoardlistwriterDTO.java
src/main/java/com/kedu/study/service/BoardService.java
src/main/resources/mapper/Board-mapper.xml

api도구 문제 해결하고 id연결 조금 했습니다 #59

api도구 문제 해결하고 id연결 조금 했습니다

---

src/main/java/com/kedu/study/controllers/AttendanceController.java
src/main/java/com/kedu/study/controllers/InsaController.java
src/main/java/com/kedu/study/dao/InsaDAO.java
src/main/java/com/kedu/study/dto/ActivityDTO.java
src/main/java/com/kedu/study/dto/AttendanceDTO.java
src/main/java/com/kedu/study/dto/DepartmentAttendanceDTO.java
src/main/java/com/kedu/study/dto/Departsimple.java
src/main/java/com/kedu/study/security/JwtFilter.java
src/main/java/com/kedu/study/service/InsaService.java
src/main/java/com/kedu/study/service/YourApplication.java
src/main/resources/mapper/insa-mapper.xml

YourApplication 라는것을 만들었는데 
스케줄러 라는 것으로 InsaService 에서 generateAnnualLeaveForAllEmployees 를 먼저 실행하기 위해 넣은 코드 입니다.

jeokaet / 근태관리 페이지 수정

---

pom.xml
src/main/java/com/kedu/study/controllers/BoardController.java
src/main/resources/mapper/Board-mapper.xml

react 리스트 부분 수정 보냅니다

---

src/main/java/com/kedu/study/controllers/BoardController.java

수정/삭제 기능 수정했습니다

---

src/main/java/com/kedu/study/service/AttendanceService.java
src/main/java/com/kedu/study/service/InsaService.java
src/main/resources/mapper/insa-mapper.xml

00:00으로 했는데 값을 안받더라고요 그래서 그거 수정했습니다

근태관리 페이지 00:00 으로 인한 오류

---

src/main/java/com/kedu/study/controllers/InsaController.java
src/main/java/com/kedu/study/dao/InsaDAO.java
src/main/java/com/kedu/study/dto/BirtdaylistDTO.java
src/main/java/com/kedu/study/service/InsaService.java
src/main/resources/mapper/insa-mapper.xml

jeokaet / 메인 페이지 생일자 생성
